[2023-04-22 15:03:55,825]: INFO -['User_Name':Sukruth]: -['filename']:client_data_preprocessing.py -['function_name']:initiate_client_preprocess_data -['line_no']:116 - Created a client_data folder.
[2023-04-22 15:03:55,825]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:22 - s3 connection is successful
[2023-04-22 15:03:55,826]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:23 - Accessing s3://census-project-files/data/
[2023-04-22 15:03:55,993]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:44 - The filename is artifacts\04_22_2023_15_03_53\client_data\data/
[2023-04-22 15:03:55,994]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:44 - The filename is artifacts\04_22_2023_15_03_53\client_data\data/2023_04_20_2023_04_22_finance_complaint.json
[2023-04-22 15:03:56,588]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:51 - artifacts\04_22_2023_15_03_53\client_data\data/2023_04_20_2023_04_22_finance_complaint.json downloaded successfully
[2023-04-22 15:03:56,588]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:55 - Archiving file from data source: s3://census-project-files/data/  to archive: s3://archive-census/archive 
[2023-04-22 15:03:58,388]: INFO -['User_Name':Sukruth]: -['filename']:s3_configuration.py -['function_name']:download_s3_files -['line_no']:57 - Data or files has been moved to archive-census succesfully 
[2023-04-22 15:03:58,388]: INFO -['User_Name':Sukruth]: -['filename']:client_data_preprocessing.py -['function_name']:preprocess_client_data_to_db -['line_no']:37 - New data path is artifacts\04_22_2023_15_03_53\client_data\data
[2023-04-22 15:03:58,619]: INFO -['User_Name':Sukruth]: -['filename']:client_data_preprocessing.py -['function_name']:preprocess_client_data_to_db -['line_no']:58 - 42104
[2023-04-22 15:04:01,051]: INFO -['User_Name':Sukruth]: -['filename']:client_data_preprocessing.py -['function_name']:initiate_client_preprocess_data -['line_no']:119 - The log mesaage is Data has been successfully dumped to finance_complaint_data
